openapi: 3.0.0
info:
  title: Random Rolls
  description: Roll a set of dice against a known set to determin statistical averages.
  version: "0.0.1"
servers:
  - url: /rndrolls
    description: Main server url
paths:
  /roll:
      post:
        summary: Roll the dice.
        description: Rolls the bag of dice, if no dice are specified rolls a default set.
        requestBody:
          description: Body must contain following key/value pairs dice_bag, num_rolls, data_set,
          dice_bag is a list of lists in the format [[x,y]], where x is number of dice and y is sides, [[2,6],[3,4]],
          num_rolls is the number of rolls in a set,
          data_set is the number of sets.
          required: false
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Set'
        responses:
          '200':
            description: Response
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Set'
          '404':
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
            description: Not Found
        operationId: connectors.rolldice
components:
  schemas:
    Error:
      properties:
        code:
          description: A code for the specific error.  Used to help in determining
            possible root causes of an error.
          type: string
        message:
          description: A message providing additional detail for an error.
          type: string
      type: object
    Message:
      example:
        level: INFO
        message: message
      properties:
        level:
          description: A level for the specific message.
          enum:
            - INFO
            - WARN
            - DEBUG
          type: string
        message:
          description: A message providing additional detail for message.
          type: string
      type: object
    KeyValue:
      description: A simple key-value pair.
      example:
        value: value
        key: key
      properties:
        key:
          description: A unique key for this pair.
          type: string
        value:
          description: A value for this pair.
          type: string
      required:
        - key
        - value
      type: object
    Set:
      properties:
        message:
          description: JSON block
          type: array
    Status:
      properties:
        code:
          description: response code
          type: string
        message:
          description: response message
          type: string